---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic-app
        image: ec2-54-226-169-77.compute-1.amazonaws.com:8082/mypets-docker/petclinic:1.16.1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:  
  name: petclinic-clusterip-service
spec:
  selector: 
    app: petclinic
  type: ClusterIP
  ports:  
  - name: http
    port: 9080
    targetPort: 8080
    protocol: TCP
